apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  labels:
    app: flask-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:    
    metadata:
      name: flask-app-pod
      labels:
        app: flask-app
    spec:
      containers:
      - name: flaskapp-container
        image: arunmg/flask-image:latest
        ports:
        - containerPort: 5000
