apiVersion: v1
kind: Pod
metadata:
  name: flask-app-pod
  labels:
    app: flask-app
spec:
  containers:
  - name: flaskapp-container
    image: arunmg/flask-image:latest
    ports:
    - containerPort: 5000